#! /bin/bash

function main() {
	ht=$1
	mt=$2
	h=$3
	m=$4
	total=$(echo "($ht*60+$mt)" | bc -l)
	echo "($h*60+$m)/$total*100" | bc -l | tr . % | sed "s/[^%]*$//"
}
echo "Usage: progress_h+min 3 40 3 20 (Answers much percent are 3h20min of 3h40 ... 90%)?"
main "$1" "$2" "$3" "$4"
