#!/bin/bash

function main() {
	if $(test -z "$1") || $(test -z "$2") || $(test -n "$3"); then
		echo "Usage: rule-of-three <part> <all>"
		echo "For example: rule-of-three 42 500"
		return 1
	fi
	part="$1"
	all="$2"
	echo "($part/$all)*100" | bc -l # rule of three.
}

main "$@"
