#!/bin/bash

function bdirbs_permanent() {
	if $(test -z "$BDIRBS_HIDE_PERM"); then
		echo "${HOME}/myroot/storedir"
		echo "${HOME}/myroot/projdir"
		echo "${HOME}/myroot/projdir/machine/machine_control_hub/"
		echo "${HOME}/myroot/projdir/machine/machine_data_config/"
	fi
}

bdirbs_permanent
