#!/usr/bin/env python3

import sys
import jdatetime

def print_usage():
    print('Usage: persian_jalali2gregorian <year> <month> <day>')
    sys.exit(1)

if len(sys.argv) != 4:
    print_usage()
y = sys.argv[1]
m = sys.argv[2]
d = sys.argv[3]
if not(d.isnumeric()) or not(y.isnumeric()):
    print_usage()

# convert non-numeric months:
def minimal_month_notation(full_notation):
     return full_notation[:3].lower() # first 3 characters in lower case.
if not(m.isnumeric()):
    m = minimal_month_notation(m)
    months=[ 'farvardin', 'ordibehesht', 'khordaad', 'tir', 'mordaad', 'shahrivar', 'mehr', 'aabaan', 'aazar', 'dey', 'bahman', 'esfand' ]
    i = 0
    for month in months:
        i = i + 1
        month = minimal_month_notation(month)
        if (m == month):
            m = str(i)

# convert to gregorian.
gregorian_date = jdatetime.date(int(y),int(m),int(d)).togregorian()
print(gregorian_date)
