#!/usr/bin/env python3

import sys
import jdatetime

if len(sys.argv) != 4:
    print('Usage: persian_jalali2gregorian <year> <month> <day>')
    sys.exit(1)
y = sys.argv[1]
m = sys.argv[2]
d = sys.argv[3]

# convert to gregorian.
jalili_date =  jdatetime.date.fromgregorian(day=int(d),month=int(m),year=int(y))
print(jalili_date)

