#!/bin/bash

function main() {
	if $(test $# -lt 2); then
		echo "Usage: git_commit_past 'YYYY-MM-DD HH:MM:SS' '<commit-message>' "
		return
	fi
	export GIT_AUTHOR_DATE="$1"
	export GIT_COMMITTER_DATE="$1"
	git commit -am "$2"
}

main
