#!/usr/bin/env bash

if $(test -z "$1") || $(test -n "$2"); then
	echo "Usage: 'web_pwnedpasswords <password>'."
fi

PASS="$1"
HASH=$(echo -n "${PASS}" | openssl dgst -sha1 | sed 's/[^ ]* //' | tr 'a-z' 'A-Z')
HASH_BEG=$(echo "${HASH}" | sed 's/\(.....\).*/\1/')
HASH_END=$(echo "${HASH}" | sed 's/.....\(.*\)/\1/')
NUM=$(curl -s "https://api.pwnedpasswords.com/range/${HASH_BEG}" | grep "${HASH_END}" | sed 's/[^:]*://' | grep -o '[0-9]*')
echo "Password '${PASS}' with hash '${HASH}' appears ${NUM} times."
