#!/bin/bash

function main() {
	DIR="$@"
	if $(test -z "$BDIRBS_HIDE_PERM"); then
		cat "$DIR" | sed "s|^~|$HOME|" | grep -v '\*'
		cat "$DIR" | sed "s|^~|$HOME|" | grep '\*' | while read x; do
			expand_glob_py "$x"
		done
	fi
}

main "$@"
