#!/usr/bin/env python3

import sys
import jdatetime

if len(sys.argv) != 4:
    print('Usage: persian_jalali2gregorian <year> <month> <day>')
    sys.exit(1)
y = sys.argv[1]
m = sys.argv[2]
d = sys.argv[3]

# convert to gregorian.
gregorian_date = jdatetime.date(int(y),int(m),int(d)).togregorian()
print(gregorian_date)

